# Docker Compose for AWS public resources scanner
version: '3.8'

services:
  aws-public-scanner:
    build: .
    container_name: aws-public-scanner
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MAX_WORKERS=${MAX_WORKERS:-10}
      - SERVICES_TO_SCAN=${SERVICES_TO_SCAN:-ec2,rds,elb,s3}
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    restart: unless-stopped
    
  # Optional: Service for real-time log visualization
  log-viewer:
    image: amir20/dozzle:latest
    container_name: log-viewer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
    environment:
      - DOZZLE_LEVEL=info
